version: "3.9"

# Variables for mysql database
x-mysql-database: &MYSQL_DATABASE devdb
x-mysql-host: &MYSQL_HOST mysqldb
x-mysql-port: &MYSQL_PORT 3306
x-mysql-user: &MYSQL_USER devuser
x-mysql-password: &MYSQL_PASSWORD devdev
x-mysql-max-conns: &MYSQL_MAX_CONNS 10

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: go-aws-sandbox-workspace
    tty: true
    volumes:
      - .:/go/src/github.com/mkaiho/go-aws-sandbox
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/mkaiho/go-aws-sandbox
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: *MYSQL_HOST
      MYSQL_PORT: *MYSQL_PORT
      MYSQL_USER: *MYSQL_USER
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      MAX_CONNS: *MYSQL_MAX_CONNS
  mysqldb:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: go-aws-sandbox-db
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_USER: *MYSQL_USER
      MYSQL_PASSWORD: *MYSQL_PASSWORD
