// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDValidator is an autogenerated mock type for the IDValidator type
type IDValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: v
func (_m *IDValidator) Validate(v string) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIDValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewIDValidator creates a new instance of IDValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIDValidator(t mockConstructorTestingTNewIDValidator) *IDValidator {
	mock := &IDValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
